Repository tinkerbell/hegel, pull requests merged in 2020-10, with the labels that each got.

#41 Moved to Github Actions from drone CI
  .drone.yml
  .github/workflows/ci.yaml
Labels: enhancement, ready-to-merge

#42 Fix Docker Action migration from v1 to v2
  .github/workflows/ci.yaml
Labels: bug

#43 Fix GitHub Action push to quay
  .github/workflows/ci.yaml
Labels: ready-to-merge

#47 Multi arch support for Docker image
  .dockerignore
  .github/workflows/ci.yaml
  Dockerfile
Labels: ready-to-merge
