Repository tinkerbell/hegel, pull requests merged in 2020-09, with the labels that each got.

#27 ENG-8083 trusted proxies
  go.mod
  go.sum
  http_server.go
  http_server_test.go
  main.go
  mock.go
  xff/xff.go
Labels: ready-to-merge

#33 Update packethost/pkg version
  go.mod
  go.sum
Labels: P1, enhancement, ready-to-merge

#35 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: ready-to-merge

#36 Update README.md
  README.md
Labels: documentation, ready-to-merge

#37 Create SUPPORT.md
  SUPPORT.md
Labels: documentation, enhancement, help wanted, ready-to-merge
